### ISSUE TITLE
[Tracking] Android build refactor: native build integrated into gradle

### ISSUE THREAD

**Issue by tobrun** [mlc-ai/mlc-llm#1295]
## Overview
This issue tracks unifying the MLC-LLM build process directly into gradle. 
We can fold the requirements of running `./prepare-libs` independently directly into gradle build process.
This could either be done by refactoring the code into gradle or by calling into the existing scripts. 

## Action Items
- [ ] figure out what minimum steps we can take to integrate a solution
- [ ] try out a variety of approaches and see what scales best
- [ ] update project documentation to match these new requirements

## Links to Related Issues and PRs
Relates to https://github.com/mlc-ai/mlc-llm/pull/1248

**Comment by tqchen** [comment]
we are moving towards android SDK to streamline some of the off tree build https://llm.mlc.ai/docs/deploy/android.html in this case the build step is still handled by part of CMake because the need to integrate custom libs, but the generated artifact now can work with gradle
