### ISSUE TITLE
[Tracking] Android build refactor: publish ready-made maven artifacts

### ISSUE THREAD

**Issue by tobrun** [mlc-ai/mlc-llm#1296]
## Overview

TBD if this is in-scope for this project. This issue tracks the possibility of distributing ready-made libraries for developers looking to integrate a specific model. Atm, the will need to go through building the project themselves while they could potentially just integrate a library instead.

Their workflow would look like:
 - open their app project
 - add a dependency for a specific llm model library publihsed by mlc-llm (eg. llama2)
 - sideload the model weights
 - use the API from the llm model library to interface with the LLM in their application code

While https://github.com/mlc-ai/mlc-llm/pull/1248 is an initial step towards this behavior, 
many things are still needed to get above in place. 

## Action Items

- [ ] set CI pipeline
- [ ] set CD pipeline
- [ ] define structure that published multi variations of the SDK for a variety of models (somethig similar to current chat config json)
- [ ] publish baselines SDKs
- [ ] update docs

## Links to Related Issues and PRs

https://github.com/mlc-ai/mlc-llm/pull/1248

**Comment by junrushao** [comment]
This is a very good idea! We should eventually make every language binding (swift, Java, C, Rust, etc) a standalone package that people could directly include in their package manager and use

**Comment by tqchen** [comment]
We migrated to a sdk based approach where the library will be packaged through mlc LLM package command
