### ISSUE TITLE
[Tracking] Mistral/OpenHermes follow-ups

### ISSUE THREAD

**Issue by CharlieFRuan** [mlc-ai/mlc-llm#1358]
## Overview

We added Mistral a while back but there are some leftover follow-ups to complete the support. This tracker compiles such remaining tasks.

## Action Items

- [x] Upload prebuilt models and weights for Mistral: https://llm.mlc.ai/docs/prebuilt_models.html
- [x] Upload prebuilt weights for OpenHermes, NeuralHermes: https://llm.mlc.ai/docs/prebuilt_models.html
- [x] Document for both Mistral and OpenHermes
- [x] Support OpenHermes in web-llm
  - Included in demo: https://webllm.mlc.ai/
- [x] Support [NeuralHermes-2.5-Mistral-7B](https://huggingface.co/mlabonne/NeuralHermes-2.5-Mistral-7B)

Some not-so-related items:

- [x] Make `tokenizer.json` change in web-llm similar to https://github.com/mlc-ai/mlc-llm/pull/1352
- [x] Populate build-from-source tutorial in https://llm.mlc.ai/docs/install/mlc_llm.html#option-2-build-from-source

Left for future:
- Remove `<|im_start|>` in chatml-like conversation template (mentioned in comments under https://github.com/mlc-ai/mlc-llm/pull/1354)

**Comment by 0xDEADFED5** [comment]
is this why process_system_prompts_() is dying on my Mistral model?

**Comment by scottorly** [comment]
Trying to load OpenHermesMistral on iOS produces the following error: `Unknown conversation template: open_hermes_mistral`. Adding the template to the factory method in `conv_templates.cc` fixes the issue.

**Comment by marekk1717** [comment]
> Trying to load OpenHermesMistral on iOS produces the following error: `Unknown conversation template: open_hermes_mistral`. Adding the template to the factory method in `conv_templates.cc` fixes the issue.

I've got the same issue on mac osx x86_64. How to recompile mlc_chat ?

**Comment by CharlieFRuan** [comment]
Hi @scottorly @marekk1717 the conversation template should now be included: https://github.com/mlc-ai/mlc-llm/pull/1385

**Comment by CharlieFRuan** [comment]
All prebuilts are documented here: https://llm.mlc.ai/docs/prebuilt_models.html
