### ISSUE TITLE
[Tracking] UX of the new compilation CLI

### ISSUE THREAD

**Issue by junrushao** [mlc-ai/mlc-llm#1364]
Actively moving towards the next-generation deployment pipeline in MLC LLM, before it is made public, we wanted to make sure the UX of our tooling being as user-friendly as possible.

## The Problem

One specific issue this thread aims to address is the massive duplication between two subcommands: `mlc_chat compile` and `mlc_chat gen_mlc_chat_config`. For more details,

- `compile` subcommand accepts the following flags:

![image](https://github.com/mlc-ai/mlc-llm/assets/22515877/656c2c27-befe-40ca-aa49-17f0ef83669e)

- `gen_mlc_chat_config` subcommand accepts the following flags:

![image](https://github.com/mlc-ai/mlc-llm/assets/22515877/0220e050-5ff0-4bc8-b97c-88ad23ab5e78)

The overlapped flags include:

- `--model`: 1) path to HF’s `config.json` or; 2) path to the folder that contains HF’s config.json; 3) name of a prebuilt HF’s `config.json`, such as `llama2_7b`.
- `--quantization`: quantization format
- `--context-window-size` (previously known as `--max-seq-len`): maximum length of the context window used in runtime
- `--sliding-window`: sliding window size for Mistral variants
- `--prefill-chunk-size`: size of chunked prefilling

In extra,

- `mlc_chat compile` comes with: `--device` , `--host` , `--opt` , `--prefix-symbols`, and
- `mlc_chat gen_mlc_chat_config` accepts: `--conv-template`

Apparently, the set of overlapped flags will continue to grow if the usecases expand to more fine-grained control of model definition and runtime behavior, for example, setting uplimits of batch size, vocab size, etc.

## The Proposal

To promote simplicity and ensure consistency between subcommands, we propose to review and revise the current `mlc_chat compile` subcommand before them going to public, particularly, the possibility to reuse `mlc-chat-config.json` produced by `gen_mlc_chat_config` subcommand.

To enumerate the usecases of `mlc_chat compile` that exist as of now or may exist in the future, its `--model` flag points to:

- W1. path to the folder that contains `config.json`, or path to `config.json`
- W2. prebuilt name of a model, e.g. `llama2_7b`
- W3. path to the folder that contains `mlc-chat-config.json`, or path to `mlc-chat-config.json`.
- W4. a HuggingFace URL, e.g. `HF://junrushao/Llama-2-7b-hf-q4f16_1`.

Assuming the primary usecases include:

- C1. Using pre-quantized models of MLC LLM hosted on HuggingFace;
- C2. Using locally quantized models by users.

It is safe to say `mlc-chat-config.json` always exists, and given the subcommand `gen_mlc_chat_config` is super lightweight (it exists out-of-box in C1, and run < 1s in C2), it is safe to assume it doesn’t bring in too much operational trouble to end users. Therefore, we propose to go all in to relying `mlc-chat-config.json` in the compilation pipeline, and concrete actionable items are in the following section.

## Action Items

We propose the following actionable items:

- [x] A1. Deprecate W1: It effectively makes `mlc-chat-config.json` a hard (but lightweight) dependency to running `compile`. #1371
- [x] A2. Introduce W3, which should follow the same logic internally but uses a much cleaner interface, see the following paragraph for more details. #1371
- [x] A3. Roll out full support for W4, which partly exists in [`python/mlc_chat/support/download.py::download_mlc_weights`](https://github.com/mlc-ai/mlc-llm/blob/dd245c1d746cf76e48bea0cafc6bcfb6de9a7559/python/mlc_chat/support/download.py#L129-L170), which allows automatic downloading and caching of pre-quantized weights provided by MLC LLM. #1374
- [x] A4. Update W2 from pre-defined `config.json` to pre-defined `mlc-chat-config.json` and allows overriding of certain flags. #1374
- [x] A5. Rename `gen_mlc_chat_config` to `gen_config`. https://github.com/mlc-ai/mlc-llm/pull/1375
- [x] A6. Automatic [--system-lib-prefix](https://github.com/mlc-ai/mlc-llm/issues/1364#issuecomment-1836954455). #1427

In terms of CLI flags, we propose to simplify the compilation interface as below:

```bash
mlc_chat compile --model /prposal-A1-A4
                 # example:
                 # 1) "HF://mlc-ai/XXX-q4f16_1"
                 # 2) "/path/mlc-chat-config.json"
                 # 3) "/path/", which contains `mlc-chat-config.json`
                 # 4) "llama2_7b", a prebuilt `mlc-chat-config.json`
                 --device "auto" --host "auto" --static-lib-prefix ""
                 --opts "flash_infer_attn=1;cublas_gemm=1"
                 --overrides "context_window_size=1024;sliding_window=1024"
                 # overrides options in `mlc-chat-config.json`
```

The comma separated sub-options in `--overrides` are already implemented for `opts` in [`python/mlc_chat/compiler/flags_optimization.py`](https://github.com/mlc-ai/mlc-llm/blob/dd245c1d746cf76e48bea0cafc6bcfb6de9a7559/python/mlc_chat/compiler/flags_optimization.py), and it is proposed to implement similar logics in [`python/mlc_chat/compiler/flags_model_config_override.py`](https://github.com/mlc-ai/mlc-llm/blob/dd245c1d746cf76e48bea0cafc6bcfb6de9a7559/python/mlc_chat/compiler/flags_model_config_override.py).
