### ISSUE TITLE
[Tracking] SLM Rollout Wrap up

### ISSUE THREAD

**Issue by CharlieFRuan** [mlc-ai/mlc-llm#1669]
## Overview

As SLM rollout is almost completed: https://github.com/mlc-ai/mlc-llm/issues/1420, there are some remaining steps to clear the confusion. 

## Action Items

**W0: Tutorial notebook as CI**
The Colab notebooks have served as an entrance for many people new to mlc-llm, and thus it would also be nice to add them as tests:
- https://github.com/mlc-ai/mlc-llm/issues/1551
- https://github.com/mlc-ai/web-llm/issues/274
- `tutorial_chat_module_getting_started.ipynb` also seem to broken
- [ ] Fix notebooks
- [ ] Add notebooks as tests

**W1: Transition from the old mlc_chat_cli to the new SLM CLI**
Afterward, we should clean up the models prefixed with `mlc-chat-` in https://huggingface.co/mlc-ai, and model libraries not in a folder: https://github.com/mlc-ai/binary-mlc-llm-libs, as these outdated and unmaintained models and weights have caused much confusion in the issues (e.g. one below, and some other instances in discord).
- https://github.com/mlc-ai/web-llm/issues/273

- [x] https://github.com/mlc-ai/mlc-llm/issues/1707
 
**W2: Model support parity**
Comparing the two directories, [python/mlc_chat/model](https://github.com/mlc-ai/mlc-llm/tree/main/python/mlc_chat/model) and [mlc_llm/relax_model](https://github.com/mlc-ai/mlc-llm/tree/main/mlc_llm/relax_model), there some architectures that are still not supported in SLM. While some could be slightly obsolete now, some may still be good to have.
- [x] stablelm
  - #1616
- [x] RWKV
  - #1787
- [x] gptj
  - https://github.com/mlc-ai/mlc-llm/pull/1751
- [x] chatglm
- [x] minigpt (perhaps wait for LLaVA)

**W3: Other compilation errors due to batching**

- [x] https://github.com/mlc-ai/mlc-llm/issues/1628

**Comment by CharlieFRuan** [comment]
Feel free to add more items!

**Comment by DavidGOrtega** [comment]
Should these be added?

 - [ ] #1616 ?
 - [ ] #1628 ?
