### ISSUE TITLE
[Tracking] Transition from the old mlc_chat_cli to the new SLM CLI

### ISSUE THREAD

**Issue by rickzx** [mlc-ai/mlc-llm#1707]
## Overview
As we have confirmed that the new CLI and JIT pipeline works, we are going to deprecate the old c++-based mlc_chat_cli, in favor of the new Python-based SLM CLI.

## Action Items

- [x] Deprecate mlc_chat_cli, in favor of  https://github.com/mlc-ai/mlc-llm/pull/1563 
- [x] Update CLI documentations and also document JIT runtime flow (with HF://)
- [x] Confirm the new flow works on metal/vulkan/cuda/rocm
- [x] Remove some of the legacy library files
- [x] Go through the issues and redirect them

**Comment by rickzx** [comment]
Done
