### ISSUE TITLE
[Tracking] Model definition migration to PagedKVCache

### ISSUE THREAD

**Issue by CharlieFRuan** [mlc-ai/mlc-llm#1749]
## Overview

Recently `PagedKVCache` was added to TVM (https://github.com/apache/tvm/pull/16273) and Llama was the first to adopt it within MLC-LLM: https://github.com/mlc-ai/mlc-llm/pull/1651. This issue tracks the progress of migrating the rest of the models to adopt this interface. The goal is to have a unified KVCache interface so that all models can benefit from future low-level optimizations. This change should not be breaking as `llm_chat.cc` currently supports both types of KVCache.

Aside from the corresponding changes that may be required on the `PagedKVCache` side (noted below), the rest of the changes for each model should be similar to the one in Llama in this PR: https://github.com/mlc-ai/mlc-llm/pull/1651

## Action Items

- [x] Migrate Mistral **(assigned)**
  - Note: This may require implementing support for sliding window attention and attention sink in `PagedKVCache`
  - #1967
- [x] Migrate Mixtral **(assigned)**
- [x] Migrate GPT-2 
  - Note: May require implementing support for non-RoPE position encoding in `PagedKVCache`
  - https://github.com/mlc-ai/mlc-llm/pull/1784
- [x] Migrate RedPajama
  - https://github.com/mlc-ai/mlc-llm/pull/1786
- [x] Migrate GPT-BigCode **(assigned)**
  - #1891
- [x] Migrate Phi **(assigned)**
- [x] Migrate QWen **(assigned)**
  - #1887
- [x] Migrate StableLM
  - #1882

## Related PRs
- https://github.com/apache/tvm/pull/16273
- https://github.com/mlc-ai/mlc-llm/pull/1651
- https://github.com/mlc-ai/web-llm/pull/293

**Comment by Hzfengsy** [comment]
One minor note: we may need to correct the KVCache memory usage after migration to PagedKVCache, current is always zero

**Comment by Nick-infinity** [comment]
Hello, I am facing below mentioned issue with TinyLllama model 

```
MLCChat failed

Stack trace:
org.apache.tvm.Base$TVMError: InternalError: Check failed: static_cast<size_t>(gfunc.num_args) == args.size() (4 vs. 0) : ValueError: Invoking function create_tir_paged_kv_cache requires 4 inputs but only 0 inputs are provided.
Stack trace:
  File "/home/bajiezi/projects/mlc-llm/3rdparty/tvm/src/runtime/relax_vm/vm.cc", line 652

	at org.apache.tvm.Base.checkCall(Base.java:173)
	at org.apache.tvm.Function.invoke(Function.java:130)
	at ai.mlc.mlcllm.ChatModule.reload(ChatModule.java:43)
	at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:642)
	at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:640)
	at ai.mlc.mlcchat.AppViewModel$ChatState.callBackend(AppViewModel.kt:543)
	at ai.mlc.mlcchat.AppViewModel$ChatState.mainReloadChat$lambda$3(AppViewModel.kt:640)
	at ai.mlc.mlcchat.AppViewModel$ChatState.$r8$lambda$JJKpoRMMpp77FzXKA0o00i8lgRA(Unknown Source:0)
	at ai.mlc.mlcchat.AppViewModel$ChatState$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.uil.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


Error message:
InternalError: Check failed: static_cast<size_t>(gfunc.num_args) == args.size() (4 vs. 0) : ValueError: Invoking function create_tir_paged_kv_cache requires 4 inputs but only 0 inputs are provided.
Stack trace:
  File "/home/bajiezi/projects/mlc-llm/3rdparty/tvm/src/runtime/relax_vm/vm.cc", line 652il.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


Error message:
InternalError: Check failed: static_cast<size_t>(gfunc.num_args) == args.size() (4 vs. 0) : ValueError: Invoking function create_tir_paged_kv_cache requires 4 inputs but only 0 inputs are provided.
Stack trace:
  File "/home/bajiezi/projects/mlc-llm/3rdparty/tvm/src/runtime/relax_vm/vm.cc", line 652

```

I think it comes from #1651

**Comment by CharlieFRuan** [comment]
@Nick-infinity Hi! Could you provide the commands you used to compile/run the model?

**Comment by Nick-infinity** [comment]
> @Nick-infinity Hi! Could you provide the commands you used to compile/run the model?

Hello @CharlieFRuan , heres my setup
1. MLC - https://github.com/mlc-ai/mlc-llm/tree/e36f20d9d3e5e6aff52b3ad7245315c9e94f9077
2. TVM - Tried Latest Unity Branch and MLC Relax repo
3. Target Device - Android OpenCL

I  have built everything from source and not using python wheel. Followed the exact steps mentioned in the Docs to compile the model and android application.

**Comment by CharlieFRuan** [comment]
@Nick-infinity I see... This is indeed a bit weird. I do not have an immediate idea on top of my head; let's keep the conversation in https://github.com/mlc-ai/mlc-llm/issues/1741!

**Comment by CharlieFRuan** [comment]
>  Migrate Mistral (assigned)

Will be working on Mistral and adding SWA/attention sink to PagedKVCache.

**Comment by anibohara2000** [comment]
> Migrate Mixtral (assigned)
Will be working on migrating Mixtral to use the PagedKVCache interface

**Comment by dusty-nv** [comment]
Any updates on the projected timeline for these?    Namely phi-2 and StableLM.  Thanks!

**Comment by Kartik14** [comment]
@dusty-nv Phi-2 is supported now after #1872

**Comment by tlopex** [comment]
I would like to handle with last two models. Thanks:)

**Comment by tqchen** [comment]
@DiegoCao is working on Qwen #1836 . and stablelm is being worked on by @tlopex  at #1882

**Comment by MasterJH5574** [comment]
StableLM by #1882 is already merged. Qwen by #1887 is ready for merge after passing CI.

**Comment by MasterJH5574** [comment]
The migration of the last model -- mistral -- is ready here https://github.com/mlc-ai/mlc-llm/pull/1967. If things go smooth, it will be merged within 2 days.
