### ISSUE TITLE
[Tracking] Migrate Rest API to MLC Serve

### ISSUE THREAD

**Issue by Kartik14** [mlc-ai/mlc-llm#1767]
## Overview

This issue tracks the migration of Current Rest API backend to use MLC Serve. MLC Serve implements a paged KV cache interface and supports batched processings of prompts. This will allow the server to handle multiple requests concurrently. 

## Action Items

- [x] Confirm performance with batch size of 1 against the old interface
- [x] Migrate all the models to use the new KV Cache interface
- [x] Update [Rest API docs](https://llm.mlc.ai/docs/deploy/rest.html) to use MLC Serve
    - #1972 
- [x] Delete old Rest API (pending finish of #1749)

## Links to Related Issues and PRs

- #1749 
- #1651 
- https://github.com/apache/tvm/pull/16273

cc @MasterJH5574 @tqchen @shreygupta2809

**Comment by xapss** [comment]
Hi guys, appreciate the work. We would love to support concurrent usage and therefore require this afaik. Do you have any timeline on this? Thanks a bunch!

**Comment by Kartik14** [comment]
@xapss Hi! This is mostly done :)

**Comment by shreygupta2809** [comment]
> @Kartik14  Almost done? :)

@xapss Hi, this has been completed.
Thanks
