### ISSUE TITLE
[Tracking] Upgrade RedPajama Support to q4f16_1

### ISSUE THREAD

**Issue by tqchen** [mlc-ai/mlc-llm#639]
Currently most of our RedPajama support were at q4f16_0, this is a tracking issue to upgrade the RedPajama support to `q4f16_1`

## Action Items

- [x] Support combined QKV and other matmul https://github.com/mlc-ai/mlc-llm/pull/667
- [x] Weight upload https://huggingface.co/mlc-ai/mlc-chat-RedPajama-INCITE-Chat-3B-v1-q4f16_1
- [x] iOS app-config update https://github.com/mlc-ai/mlc-llm/pull/672
- [x] prebuilt metal lib for M1
- [x] prebuilt dll for windows 
- [x] prebuilt vulkan lib for linux
- [x] Update the docs to migrate remaining `q4f16_0` to `q4f16_1` https://github.com/mlc-ai/mlc-llm/pull/673

**Comment by MasterJH5574** [comment]
Happy to work on this in this week

**Comment by MasterJH5574** [comment]
Updated the tracking with QKV and other matmul combination item.

**Comment by MasterJH5574** [comment]
Closed as all finished.
