### ISSUE TITLE
[Tracking] Enable Rocm Support

### ISSUE THREAD

**Issue by tqchen** [mlc-ai/mlc-llm#644]
## Overview

This is a tracking issue for bringing in rocm support to mlc-chat. At the current state this issue remains high-level, and we will expand working items (possibly in new issues).

## Action Items

- [x] Enable tvm unity rocm build through LLVM
- [x] Confirm dlight performance of rocm https://github.com/mlc-ai/dlight-bench/pull/5/ https://github.com/apache/tvm/pull/15490
- [x] Confirm e2e build for rocm https://github.com/mlc-ai/mlc-llm/pull/652

## Links to Related Isssue

- https://github.com/mlc-ai/mlc-llm/issues/632
