### ISSUE TITLE
[Tracking] Enable OpenCL Support

### ISSUE THREAD

**Issue by Kathryn-cat** [mlc-ai/mlc-llm#648]
## Overview

This is a tracking issue for bringing in OpenCL support to mlc-chat, in order to run on devices like some Android Phones etc. At the current state, this issue remains high-level, and we will expand working items (possibly in new issues).

## Action Items

- [ ] Enable tvm unity OpenCL build
- [ ] Confirm dlight performance of OpenCL
- [ ] Confirm e2e build for OpenCL

## Links to Related Isssue

- https://github.com/mlc-ai/mlc-llm/issues/640
