### ISSUE TITLE
[Tracking] More User-friendly Python API

### ISSUE THREAD

**Issue by Kathryn-cat** [mlc-ai/mlc-llm#650]
## Overview

At the moment the Python API for MLC Chat does not support high-level API, and only contains low-level functions with less well-documented behaviors, which might confuse users on how to use and customize MLC Chat. The error messages are also not clear enough to give user guidance when things go wrong. Moreover, some users would like to benchmark the performance using Python API, which is lacking now. 

## Action Items

We have opened a PR for bringing more user-friendly Python API, see #645 
Specifically, we cover the following:
- [x] Bringing in high-level functions for easy creation, generation, and timing of the MLC chat module, so that users can pick up MLC chat module real quick 
- [x] Clearer error messages for proper guidance when things go wrong
- [x] Better documentation with getting started examples that users can directly copy-paste to try out
- [x] Easier customization of the chat module, i.e. maximum generation length
- [x] Benchmarks for running end-to-end models in the Python API #688 
- [x] Neat usage of Gradio and Rest API

## Links to Related Isssue

- https://github.com/mlc-ai/mlc-llm/issues/635
- https://github.com/mlc-ai/mlc-llm/issues/620
- https://github.com/mlc-ai/mlc-llm/issues/608

**Comment by Kathryn-cat** [comment]
This issue is finished now.
