### ISSUE TITLE
[Tracking] Performant CUDA Prebuilts

### ISSUE THREAD

**Issue by junrushao** [mlc-ai/mlc-llm#658]
We noticed lately there is a surge of interest in CUDA performance in open-source LLM libraries. While MLC provides competitive performance, CUDA is not sufficiently documented and thus not widely accessible to users, as MLC documentation currently focuses universal deployment across iOS/Android/JavaScript/C++ with Metal/Vulkan/OpenCL-capable GPUs.

I created a Docker-based reproducible perf bench for CUDA performance over the weekend (https://github.com/junrushao/llm-perf-bench/), demonstrating a viable approach to deliver competitive CUDA performance from MLC, but indeed it is less sufficiently accessible yet.

To make CUDA performance easily reproducible with or without Docker, we use this roadmap to track actionable items

## Bugfixing & Code upstreaming

- [x] Codegen bug fixing in GPTNeoX (as part of #639) @MasterJH5574 
- [x] Split-RoPE fusion: https://github.com/mlc-ai/mlc-llm/pull/654

## Prebuilt Library

- [x] Enable proper CUDA support in TVM Unity pip wheel: https://github.com/mlc-ai/package/pull/43
- [x] Multiarch fatbin @Hzfengsy https://github.com/mlc-ai/mlc-llm/pull/686
- [x] Migrate [llm-perf-bench](https://github.com/junrushao/llm-perf-bench/) to use mainline pip wheel @junrushao 
- [ ] CUDA support in mlc_chat_cli and Python API @junrushao 

## Documentation

- [ ] Mention CUDA on the try out page
