### ISSUE TITLE
[Tracking] Documentation for Python API Overhaul

### ISSUE THREAD

**Issue by CharlieFRuan** [mlc-ai/mlc-llm#682]
## Overview

Update the documentation according to the recent Python API Overhaul (#645).

## Action Items

- [ ] ~~README.md revamp~~ (Will follow up separately)
- [x] Put a Python version in [Try Out MLC Chat](https://mlc.ai/mlc-llm/docs/get_started/try_out.html) #700
- [x] Add a Get Started section in [Python API page](https://mlc.ai/mlc-llm/docs/deploy/python.html) #687
  - [x] Include instructions on setting everything up
  - [x] Update current tutorial notebooks to use the new Python API #702
  - [x] Add a tutorial section, linking to current tutorial notebooks
- [x] Update API ref section in [Python API page](https://mlc.ai/mlc-llm/docs/deploy/python.html)
  - [x] Include example sections for ChatModule

## Links to Related Issues and PRs
- #645 
- #650 
- #687 (the PR for this tracker)
