### ISSUE TITLE
[Tracking] New Model Requests

### ISSUE THREAD

**Issue by CharlieFRuan** [mlc-ai/mlc-llm#692]
## Overview

This is a tracker for all new model requests from the community. The end goal is to have prebuilt models for all these models (either from us, or from the community -- see below).

## Help Wanted
We would really appreciate it if you could contribute to the project by compiling any requested model listed below. 

You could:
1.  Follow the detailed steps listed in [this Python notebook](https://github.com/mlc-ai/notebooks/blob/main/mlc-llm/tutorial_extensions_to_more_model_variants.ipynb) (runnable in Colab)
2. Upload your compiled model to your huggingface repo (also covered in the notebook)
3. Post the link to your huggingface repo below so that others may benefit from your great work!

For more information (e.g. what architectures are currently supported) see: https://mlc.ai/mlc-llm/docs/prebuilt_models.html

To see what prebuilt models we currently have: https://huggingface.co/mlc-ai

Thank you!

## Models with Supported Architecture

- [x] [georgesung/llama2_7b_chat_uncensored](https://huggingface.co/georgesung/llama2_7b_chat_uncensored)
  - #586 
  - Prebuilt uploaded: [mlc-ai/mlc-chat-llama2-7b-chat-uncensored-q4f16_1](https://huggingface.co/mlc-ai/mlc-chat-llama2-7b-chat-uncensored-q4f16_1)
  - Prebuilt uploaded: [mlc-ai/mlc-chat-llama2-7b-chat-uncensored-q4f32_1](https://huggingface.co/mlc-ai/mlc-chat-llama2-7b-chat-uncensored-q4f32_1)

- [x] [FlagAlpha/Llama2-Chinese-7b-Chat](https://huggingface.co/FlagAlpha/Llama2-Chinese-7b-Chat)
  - #593 
  - Prebuilt uploaded: [mlc-ai/mlc-chat-FlagAlpha-Llama2-Chinese-7b-Chat-q4f16_1](https://huggingface.co/mlc-ai/mlc-chat-FlagAlpha-Llama2-Chinese-7b-Chat-q4f16_1)
  - Prebuilt uploaded: [mlc-ai/mlc-chat-FlagAlpha-Llama2-Chinese-7b-Chat-q4f32_1](https://huggingface.co/mlc-ai/mlc-chat-FlagAlpha-Llama2-Chinese-7b-Chat-q4f32_1)

- [x] [Tap-M/Luna-AI-Llama2-Uncensored](https://huggingface.co/Tap-M/Luna-AI-Llama2-Uncensored) (q3)
  - #633 
  - Prebuilt uploaded: [acalatrava/mlc-chat-luna-ai-llama2-7b-chat-uncensored-q3f16_1](https://huggingface.co/acalatrava/mlc-chat-luna-ai-llama2-7b-chat-uncensored-q3f16_1)

- [ ] [Guanaco](https://huggingface.co/JosephusCheung/Guanaco)
  - #336 
  - Supported by PR #497; prebuilt models not uploaded yet

- [ ] [HuggingFaceH4/starchat-alpha](https://huggingface.co/HuggingFaceH4/starchat-alpha)
   - #214

- [ ] [Moss](https://huggingface.co/fnlp/moss-moon-003-sft)
   - #174 

- [x] [CodeLlama](https://about.fb.com/news/2023/08/code-llama-ai-for-coding/) (f32 in wasam specifically)
  - https://github.com/mlc-ai/web-llm/issues/179

## Models with Unsupported Architecture
- [ ] [ReplitLM](https://huggingface.co/replit/replit-code-v1-3b)
  - #514 
- [ ] [Bloom model of BigScience](https://github.com/huggingface/transformers/tree/main/src/transformers/models/bloom)
  - #492 
- [ ] [Falcon](https://huggingface.co/blog/falcon)
  - #487 

## Others
- [ ] 100+B models in general
  - #616

**Comment by MrJungle1** [comment]
@CharlieFRuan I am very happy to contribute my code, but I need some information to get started. Can you provide some more information or documents?

**Comment by CharlieFRuan** [comment]
@MrJungle1 Hi, thank you for the interest! Documentation can be found here: https://llm.mlc.ai/docs/

Specifically, compiling models can be located here: https://llm.mlc.ai/docs/compilation/compile_models.html

**Comment by MrJungle1** [comment]
@CharlieFRuan Hello, thank you for your reply. I read this doc, but I don’t seem to find what I want. If I want to support a new model_type, such as "model_type": "qwen", where should I start?

**Comment by MrJungle1** [comment]
Great, thank you for your reply, LGTM!

**Comment by niutech** [comment]
Could you please add Microsoft Phi-1.5 and Phi-2 to the list (#905)? Thanks.

**Comment by CharlieFRuan** [comment]
@niutech Phi1.5 and phi2 are now supported: https://llm.mlc.ai/docs/prebuilt_models.html#level-1-supported-model-architectures-the-all-in-one-table

**Comment by CharlieFRuan** [comment]
Replacing this page with https://github.com/orgs/mlc-ai/projects/2. Submit a request to the dashboard following https://github.com/mlc-ai/mlc-llm/issues/1042
