### ISSUE TITLE
[Tracking] Add WizardLM, WizardMATH, and WizardCoder

### ISSUE THREAD

**Issue by CharlieFRuan** [mlc-ai/mlc-llm#739]
## Overview

Make explicit support for [the Wizard LLMs](https://huggingface.co/WizardLM). Then demo each on a Colab notebook.
- WizardLM 13B 
- WizardMATH 7B
- WizardMATH 13B
- WizardCoder 15B

## Action Items

- [x] Conversation templates:
  - #741 
  - [x] Create a new conversation template for WizardMATH and WizardCoder
  - [x] Change current `wizardlm` template to be for 7B only (does not support multi-round)
  - [x] Update WizardLM 13B/70B to use `vicuna_v1.1` (supports multi-round)
  - [x] Finally change `argparse_postproc_common` in `mlc_llm` so that each model has the right template after compilation
- [x] Upload compiled models for `WizardMATH` (all others are on huggingface already)
- [x] Upload model library for `WizardCoder` (different architecture than others)
- [x] Upload model library for `WizardMATH` (currently not compatible with llama2) 
- [x] Make a Colab notebook to demo all
- [x] Add support to web-llm
  - Available on https://webllm.mlc.ai/

See demo here: https://github.com/mlc-ai/notebooks/blob/main/mlc-llm/models/demo_WizardLM_Math_Coder.ipynb

**Comment by ChiYeungLaw** [comment]
Thank you for the support for the Wizard models.

**Comment by Sing-Li** [comment]
Sorry but I can't find the `metal.so`  to support Apple M1/M2 for these models.
