### ISSUE TITLE
[Tracking][BugFix] iOS/Android "Could not convert TVM object of type runtime.Closure to a string."

### ISSUE THREAD

**Issue by MasterJH5574** [mlc-ai/mlc-llm#936]
The issue is the same as described in #906, while now it only happens for Android and iOS.

We are now working on a fix but it might take some time.

For anyone who suffers from this issue, you can checkout commit 275b43c1affe295ed0bd76ea0030bc655f29aa0a as a workaround when the fix is still in progress.

Create this issue thread to track and to report back.

- [x] Bug fixed in codebase #938
- [x] Android build validated
- [x] iOS build validated

**Comment by MasterJH5574** [comment]
Validated on both iOS and Android. Closing the issue now.

**Comment by acalatrava** [comment]
I now receive another error...

```
/mlc/mlc-llm/3rdparty/tvm/include/tvm/runtime/packed_func.h:1973: InternalError: Check failed: type_code_ == kTVMObjectHandle (9 vs. 8) : expected Object but got ModuleHandle
Stack trace:
  [bt] (0) 1   MLCChat                             0x0000000100621784 tvm::runtime::detail::LogFatal::Entry::Finalize() + 68
  [bt] (1) 2   MLCChat                             0x0000000100621740 tvm::runtime::detail::LogFatal::Entry::Finalize() + 0
  [bt] (2) 3   MLCChat                             0x00000001006207b4 __clang_call_terminate + 0
  [bt] (3) 4   MLCChat                             0x000000010062f068 tvm::runtime::String tvm::runtime::TVMPODValue_::AsObjectRef<tvm::runtime::String>() const + 1300
  [bt] (4) 5   MLCChat                             0x000000010062f1d4 tvm::runtime::TVMArgValue::operator std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>() const + 192
  [bt] (5) 6   MLCChat                             0x000000010062eafc tvm::runtime::PackedFuncValueConverter<tvm::runtime::String>::From(tvm::runtime::TVMArgValue const&) + 104
  [bt] (6) 7   MLCChat                             0x0000000100635e2c mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::'lambda'(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const + 724
  [bt] (7) 8   MLCChat                             0x0000000100635b4c tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::'lambda'(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)>>::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 40
  [bt] (8) 9   MLCChat                             0x000000010060456c -[ChatModule reload:modelPath:appConfigJson:] + 520
```

maybe am I missing something @MasterJH5574? I made sure to do a `git submodule update --recursive` and remove the `build` folder before doing `./prepare_libs.sh`...

The CLI version compiles and works well

**Comment by spectrometerHBH** [comment]
@acalatrava 
Is your mlc-llm repo up-to-date? especially here: https://github.com/mlc-ai/mlc-llm/blob/main/cpp/llm_chat.cc#L473

**Comment by acalatrava** [comment]
My bad... I was using my fork that was not synced with yours... :sweat:

Yes, I can confirm the fix is indeed working.

**Comment by MasterJH5574** [comment]
@acalatrava Thanks for confirming! Glad to here it works
